server:
  port: 6001

spring:
  application:
    name: log-consumer-service

  kafka:
    listener:
      observation-enabled: true
    consumer:
      bootstrap-servers: localhost:9092
      group-id: docore-log-consumer-group  # Identifies this listener
      auto-offset-reset: earliest          # Read from start if we missed anything
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # Allows converting JSON back to Java objects
        spring.json.value.default.type: "com.docore.consumer.entity.LogEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 3s

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # Default
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: "w3c,b3"
# Custom variable so we don't hardcode the topic name in Java
docore:
  kafka:
    topic: docore-logs-topic

resilience4j:
  circuitbreaker:
    instances:
      elasticBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5               # Check the last 5 requests
        failureRateThreshold: 50           # If 50% (2.5 failures) occur, OPEN the circuit
        waitDurationInOpenState: 10000ms   # Wait 10 seconds before trying again
        permittedNumberOfCallsInHalfOpenState: 3 # Allow 3 test requests to check if DB is back
        automaticTransitionFromOpenToHalfOpenEnabled: true