server:
  port: 6000

spring:
  application:
    name: log-producer-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      observation-enabled: true
      # Serializers: Strings for Keys, JSON for Values (LogEvent objects)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # Default
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: "w3c,b3"

# Custom config for our application logic
docore:
  kafka:
    topic: docore-logs-topic