name: Build and Deploy to Docker Hub

on:
  push:
    branches: [ "main", "advancement" ]
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'docs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3a. Build Producer JAR (Go into subfolder)
      - name: Build Producer JAR
        run: mvn clean package -DskipTests
        working-directory: ./log-producer-service

      # 3b. Build Consumer JAR (Go into subfolder)
      - name: Build Consumer JAR
        run: mvn clean package -DskipTests
        working-directory: ./log-consumer-service

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build & Push Producer Image
      - name: Build & Push Producer Image
        uses: docker/build-push-action@v5
        with:
          context: ./log-producer-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docore-producer:latest

      # 6. Build & Push Consumer Image
      - name: Build & Push Consumer Image
        uses: docker/build-push-action@v5
        with:
          context: ./log-consumer-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docore-consumer:latest